"""诊断题库种子 — Onboarding 三步向导的 10 题诊断（labs.tag = 'diagnostic'）

每领域 10 道客观单选题（quiz），每题绑定一个知识节点（code -> node_id），
供 /api/onboarding/questions 按领域拉取、/api/onboarding/diagnose 按节点聚合初始化画像。
幂等：已存在 diagnostic 标签的 lab 时跳过。
"""
from sqlalchemy import select, func

from models.database import KnowledgeNode, Lab

# 题目结构：code 知识节点码 / title 简短标题 / question 题干 / options 4 选项 /
# answer 正确选项下标 / explanation 解析 / difficulty 难度
DIAGNOSTIC_QUESTIONS = {
    "programming": [
        {"code": "PY_INTRO", "title": "Python 语言特征", "difficulty": "easy",
         "question": "下列关于 Python 的说法哪一项是正确的？",
         "options": ["Python 是静态类型语言，变量类型编译期确定", "Python 是动态类型且强类型语言", "Python 是弱类型语言，'1' + 1 会自动转换", "Python 代码必须先显式编译成机器码才能运行"],
         "answer": 1,
         "explanation": "Python 变量类型在运行期确定（动态类型），但不同类型间不会隐式转换（强类型），'1' + 1 会抛出 TypeError。"},
        {"code": "PY_ENV", "title": "虚拟环境的作用", "difficulty": "easy",
         "question": "使用 venv 创建虚拟环境的核心目的是什么？",
         "options": ["提升 Python 代码运行速度", "为不同项目隔离依赖包版本，避免冲突", "让 Python 程序脱离解释器独立运行", "自动升级所有第三方库到最新版"],
         "answer": 1,
         "explanation": "虚拟环境为每个项目提供独立的 site-packages，项目 A 用 requests 2.x、项目 B 用 3.x 互不干扰。"},
        {"code": "PY_RUN", "title": "REPL 与脚本模式", "difficulty": "easy",
         "question": "关于交互模式（REPL）与脚本模式的区别，正确的是？",
         "options": ["REPL 中表达式的值会自动回显，脚本模式需要 print 才输出", "脚本模式不支持定义函数", "REPL 无法导入第三方模块", "两种模式的语法规则不同"],
         "answer": 0,
         "explanation": "REPL 是读取-求值-打印循环，输入 1+1 直接回显 2；脚本模式按流程执行，输出需显式 print。语法本身一致。"},
        {"code": "PY_VAR_EXP", "title": "变量与引用", "difficulty": "medium",
         "question": "执行 a = [1, 2]; b = a; b.append(3) 后，a 的值是什么？",
         "options": ["[1, 2]", "[1, 2, 3]", "[3]", "抛出异常"],
         "answer": 1,
         "explanation": "Python 变量是对象的引用，b = a 让两个名字指向同一列表，通过 b 修改会反映在 a 上。"},
        {"code": "PY_VAR_EXP", "title": "海象运算符", "difficulty": "hard",
         "question": "海象运算符 := 的作用是什么？",
         "options": ["定义常量", "在表达式内部完成赋值并返回该值", "比较两个对象是否为同一引用", "声明全局变量"],
         "answer": 1,
         "explanation": "如 while (line := f.readline()): 在条件表达式中同时完成赋值与判断，减少重复调用。"},
        {"code": "PY_DATATYPES", "title": "浮点精度", "difficulty": "medium",
         "question": "0.1 + 0.2 == 0.3 在 Python 中的结果是？",
         "options": ["True", "False", "抛出异常", "结果随平台不同而不同"],
         "answer": 1,
         "explanation": "IEEE 754 二进制浮点无法精确表示 0.1 与 0.2，相加结果为 0.30000000000000004，比较应使用 math.isclose。"},
        {"code": "PY_FLOW", "title": "循环 else 子句", "difficulty": "hard",
         "question": "for 循环的 else 子句在什么情况下执行？",
         "options": ["循环体一次都没执行时", "循环被 break 中断时", "循环正常跑完、没有被 break 中断时", "循环内发生异常时"],
         "answer": 2,
         "explanation": "for/while 的 else 在循环自然结束时执行，常用于'搜索未找到'场景；break 跳出则不执行。"},
        {"code": "PY_FLOW", "title": "range 边界", "difficulty": "easy",
         "question": "list(range(1, 5)) 的结果是？",
         "options": ["[1, 2, 3, 4, 5]", "[1, 2, 3, 4]", "[0, 1, 2, 3, 4]", "[2, 3, 4, 5]"],
         "answer": 1,
         "explanation": "range(start, stop) 含头不含尾，生成 1 到 4。"},
        {"code": "PY_MODULES", "title": "模块导入机制", "difficulty": "medium",
         "question": "包目录中 __init__.py 文件的作用是什么？",
         "options": ["存放包的测试用例", "标识目录为包，并在包被导入时执行、可控制暴露的接口", "编译包内所有模块为字节码", "声明包依赖的第三方库版本"],
         "answer": 1,
         "explanation": "__init__.py 使目录成为常规包，导入包时执行其代码，常配合 __all__ 精细化控制对外接口。"},
        {"code": "PY_PEP8", "title": "PEP8 命名规范", "difficulty": "easy",
         "question": "按 PEP8 规范，下列命名正确的组合是？",
         "options": ["函数 getUserName，类 user_profile", "函数 get_user_name，类 UserProfile", "函数 GetUserName，类 USERPROFILE", "函数 get-user-name，类 User_Profile"],
         "answer": 1,
         "explanation": "PEP8 约定函数与变量用蛇形命名（snake_case），类名用驼峰命名（PascalCase）。"},
    ],
    "dsa": [
        {"code": "PY_SEQ", "title": "切片操作", "difficulty": "easy",
         "question": "s = 'abcdef'，则 s[1:4] 的结果是？",
         "options": ["'abcd'", "'bcd'", "'bcde'", "'abc'"],
         "answer": 1,
         "explanation": "切片含起始下标、不含结束下标：下标 1 到 3 为 'bcd'。"},
        {"code": "PY_LIST", "title": "列表推导式", "difficulty": "medium",
         "question": "[x * 2 for x in range(4) if x % 2 == 0] 的结果是？",
         "options": ["[0, 2, 4, 6]", "[0, 4]", "[2, 6]", "[0, 2, 4]"],
         "answer": 1,
         "explanation": "range(4) 中偶数为 0 和 2，各乘 2 得 [0, 4]。"},
        {"code": "PY_TUPLE", "title": "元组不可变陷阱", "difficulty": "hard",
         "question": "t = (1, [2, 3])，下列哪个操作不会抛出异常？",
         "options": ["t[0] = 9", "t[1] = [9]", "t[1].append(4)", "del t[0]"],
         "answer": 2,
         "explanation": "元组本身不可变（不能替换槽位），但槽位里的可变对象（列表）内容可以修改——这是经典的嵌套可变陷阱。"},
        {"code": "PY_SET", "title": "集合运算", "difficulty": "easy",
         "question": "{1, 2, 3} & {2, 3, 4} 的结果是？",
         "options": ["{1, 2, 3, 4}", "{2, 3}", "{1, 4}", "{1}"],
         "answer": 1,
         "explanation": "& 为交集运算，两个集合共有的元素为 2 和 3；集合基于哈希表，查找平均 O(1)。"},
        {"code": "PY_DICT", "title": "字典安全取值", "difficulty": "easy",
         "question": "当键可能不存在时，哪种取值方式不会抛出 KeyError？",
         "options": ["d['key']", "d.get('key')", "d.pop('key')", "d['key'] or None"],
         "answer": 1,
         "explanation": "get 在键缺失时返回 None（或指定默认值）；下标访问与无默认值的 pop 都会抛 KeyError。"},
        {"code": "PY_STR", "title": "f-string 格式化", "difficulty": "easy",
         "question": "name = 'Py'; 下列哪项输出 'Hello Py!'？",
         "options": ["print('Hello name!')", "print(f'Hello {name}!')", "print('Hello ' + name + !)", "print(f'Hello name!')"],
         "answer": 1,
         "explanation": "f-string 用花括号内插变量值；不加花括号或不加 f 前缀都只是普通文本。"},
        {"code": "PY_SCOPE", "title": "LEGB 作用域", "difficulty": "medium",
         "question": "函数内直接对全局变量赋值前未声明 global，会发生什么？",
         "options": ["直接修改全局变量", "创建一个同名的局部变量，全局变量不受影响", "抛出 SyntaxError", "自动提升为闭包变量"],
         "answer": 1,
         "explanation": "赋值语句默认在当前局部作用域创建名字（LEGB 的 L），修改全局需显式 global 声明。"},
        {"code": "PY_PARAMS", "title": "可变默认参数", "difficulty": "hard",
         "question": "def f(x, acc=[]): acc.append(x); return acc — 连续调用 f(1)、f(2) 后第二次返回什么？",
         "options": ["[2]", "[1, 2]", "[2, 1]", "抛出异常"],
         "answer": 1,
         "explanation": "默认参数在函数定义时求值一次并被所有调用共享，可变默认值会累积状态——应改用 acc=None 再在函数内初始化。"},
        {"code": "PY_CLOSURE", "title": "闭包与 nonlocal", "difficulty": "medium",
         "question": "嵌套函数要修改外层函数的局部变量，需要使用哪个关键字？",
         "options": ["global", "nonlocal", "static", "outer"],
         "answer": 1,
         "explanation": "nonlocal 声明名字来自最近的外层（非全局）作用域，使闭包可以改写捕获的变量。"},
        {"code": "PY_DECORATOR", "title": "装饰器本质", "difficulty": "medium",
         "question": "@decorator 修饰函数 f 等价于下列哪种写法？",
         "options": ["f = decorator(f)", "decorator = f(decorator)", "f = f(decorator)", "decorator(f) 且 f 保持不变"],
         "answer": 0,
         "explanation": "装饰器是接收函数并返回新函数的可调用对象，@语法糖等价于 f = decorator(f)。"},
    ],
    "organization": [
        {"code": "PY_OOP_BASE", "title": "实例与类", "difficulty": "easy",
         "question": "__init__ 方法的第一个参数 self 代表什么？",
         "options": ["类本身", "正在创建/操作的实例对象", "父类的引用", "模块命名空间"],
         "answer": 1,
         "explanation": "self 是约定俗成的实例引用名，绑定方法调用时由解释器自动传入当前实例。"},
        {"code": "PY_CLASS_MEMBER", "title": "名称改写机制", "difficulty": "medium",
         "question": "类中定义的 __secret 属性（双下划线前缀）在外部如何访问？",
         "options": ["obj.__secret", "obj._secret", "obj._ClassName__secret", "完全无法访问"],
         "answer": 2,
         "explanation": "双下划线触发名称改写（name mangling），实际存储为 _ClassName__secret——是防误用混淆而非真正的私有。"},
        {"code": "PY_PROPERTY", "title": "property 拦截", "difficulty": "medium",
         "question": "@property 装饰器的典型用途是什么？",
         "options": ["把方法变成类方法", "让方法可以像属性一样访问，并可在 setter 中做写入校验", "缓存方法的返回值", "把属性变成只能在类内部访问"],
         "answer": 1,
         "explanation": "property 把属性访问转为方法调用，obj.x 读走 getter、obj.x = v 走 setter，可拦截非法赋值。"},
        {"code": "PY_OOP_METH", "title": "三种方法辨析", "difficulty": "medium",
         "question": "@classmethod 与 @staticmethod 的关键区别是？",
         "options": ["classmethod 只能被类调用，staticmethod 只能被实例调用", "classmethod 第一个参数接收类本身（cls），staticmethod 不接收隐式参数", "staticmethod 运行更快且可以访问实例属性", "两者完全等价"],
         "answer": 1,
         "explanation": "classmethod 隐式接收 cls，适合工厂方法；staticmethod 就是放在类命名空间里的普通函数。"},
        {"code": "PY_OOP_INHERIT", "title": "MRO 解析顺序", "difficulty": "hard",
         "question": "多重继承下 Python 用什么算法确定方法解析顺序（MRO）？",
         "options": ["深度优先搜索", "广度优先搜索", "C3 线性化算法", "按字母顺序"],
         "answer": 2,
         "explanation": "Python 3 使用 C3 线性化：保持局部优先序且每个类只出现一次，super() 沿 MRO 链依次调用。"},
        {"code": "PY_MIXIN", "title": "Mixin 设计", "difficulty": "medium",
         "question": "Mixin 类的典型特征是什么？",
         "options": ["必须定义 __init__ 并管理完整状态", "提供一组可复用行为，不单独实例化，通过多继承装配进目标类", "只能包含类属性不能包含方法", "必须继承自 abc.ABC"],
         "answer": 1,
         "explanation": "Mixin 是行为切片：如 JSONSerializableMixin 提供 to_json，配合多继承无侵入地扩展类能力。"},
        {"code": "PY_MAGIC", "title": "魔术方法", "difficulty": "medium",
         "question": "要让对象支持 obj(x) 这样的函数式调用，需要实现哪个魔术方法？",
         "options": ["__init__", "__call__", "__getitem__", "__invoke__"],
         "answer": 1,
         "explanation": "__call__ 使实例成为可调用对象；__getitem__ 对应下标访问，__invoke__ 不存在。"},
        {"code": "PY_ITER", "title": "迭代器协议", "difficulty": "medium",
         "question": "一个对象要成为迭代器（iterator），必须实现哪组方法？",
         "options": ["__iter__ 和 __next__", "__len__ 和 __getitem__", "__enter__ 和 __exit__", "__init__ 和 __del__"],
         "answer": 0,
         "explanation": "迭代器协议要求 __iter__ 返回自身、__next__ 产出下一个值并在耗尽时抛 StopIteration。"},
        {"code": "PY_ITER", "title": "生成器特性", "difficulty": "medium",
         "question": "含有 yield 的函数被调用时会发生什么？",
         "options": ["立即执行函数体并返回所有值的列表", "返回一个生成器对象，函数体在迭代时才惰性执行", "抛出语法错误", "在后台线程中执行函数体"],
         "answer": 1,
         "explanation": "yield 使函数成为生成器工厂：调用只创建生成器，每次 next 才推进到下一个 yield，实现惰性流式产出。"},
        {"code": "PY_META", "title": "元类概念", "difficulty": "hard",
         "question": "关于元类（metaclass）的说法正确的是？",
         "options": ["元类是类的类，控制类对象本身的创建过程", "元类只是抽象基类的别名", "元类用于在运行时删除类", "普通类无法指定元类"],
         "answer": 0,
         "explanation": "类本身也是对象，默认由 type 创建；自定义元类（继承 type）可在类定义时注入校验、注册等元编程逻辑。"},
    ],
    "os": [
        {"code": "PY_GIL", "title": "GIL 的本质", "difficulty": "medium",
         "question": "CPython 的 GIL（全局解释器锁）导致的直接后果是？",
         "options": ["Python 无法创建多个线程", "同一进程内同一时刻只有一个线程执行 Python 字节码", "所有 I/O 操作都被串行化", "多进程之间无法通信"],
         "answer": 1,
         "explanation": "GIL 保证解释器内部状态安全，代价是 CPU 密集型多线程无法利用多核；I/O 阻塞时会释放 GIL。"},
        {"code": "PY_GIL", "title": "GIL 与任务类型", "difficulty": "medium",
         "question": "在 CPython 中，多线程对哪类任务仍然有明显加速效果？",
         "options": ["纯数值计算", "I/O 密集型任务（网络请求、文件读写）", "图像像素级处理", "大矩阵乘法"],
         "answer": 1,
         "explanation": "线程在等待 I/O 时释放 GIL，其他线程得以运行，因此 I/O 并发受益；CPU 密集应改用多进程。"},
        {"code": "PY_GIL", "title": "绕过 GIL", "difficulty": "hard",
         "question": "要让 CPU 密集型 Python 程序真正利用多核，最直接的方案是？",
         "options": ["增加线程数量", "使用 multiprocessing 多进程", "把代码放进 try-except", "调高线程优先级"],
         "answer": 1,
         "explanation": "每个进程有独立解释器与 GIL，多进程实现物理并行；NumPy 等 C 扩展在计算时释放 GIL 也是常见途径。"},
        {"code": "PY_CONCURRENT", "title": "线程安全", "difficulty": "medium",
         "question": "多线程同时对同一计数器执行 count += 1 可能丢失更新，标准解决方式是？",
         "options": ["把变量声明为全局", "使用 threading.Lock 保护临界区", "增加 sleep 拉开时间差", "把线程数降为 2"],
         "answer": 1,
         "explanation": "count += 1 是读-改-写三步非原子操作，需要互斥锁保证临界区串行执行。"},
        {"code": "PY_CONCURRENT", "title": "进程与线程", "difficulty": "easy",
         "question": "关于进程与线程的说法正确的是？",
         "options": ["同一进程内的线程共享内存空间，进程之间默认隔离", "线程之间默认隔离，进程共享内存", "进程是 CPU 调度的最小单位", "线程崩溃不会影响所在进程"],
         "answer": 0,
         "explanation": "线程共享所在进程的地址空间（因此才有竞态问题），进程间需要 IPC 通信；线程是调度最小单位。"},
        {"code": "PY_CONCURRENT", "title": "并发池", "difficulty": "medium",
         "question": "concurrent.futures.ThreadPoolExecutor 的主要价值是？",
         "options": ["绕过 GIL 实现多核并行", "复用固定数量的线程执行任务队列，避免频繁创建销毁线程", "自动把线程升级为进程", "保证任务按提交顺序完成"],
         "answer": 1,
         "explanation": "池化托管线程生命周期，submit/map 提交任务返回 Future；完成顺序取决于任务耗时而非提交顺序。"},
        {"code": "PY_CONCURRENT", "title": "守护线程", "difficulty": "hard",
         "question": "daemon=True 的守护线程有什么行为特征？",
         "options": ["优先级高于普通线程", "主线程退出时守护线程被直接终止，不会阻止进程结束", "自动重启崩溃的任务", "只能执行 I/O 操作"],
         "answer": 1,
         "explanation": "守护线程是后台服务角色，进程存活与否只取决于非守护线程；因此清理逻辑不能放在守护线程里。"},
        {"code": "PY_ASYNC", "title": "async/await 语义", "difficulty": "medium",
         "question": "在 async 函数中 await 一个耗时的网络请求时，事件循环在做什么？",
         "options": ["阻塞等待该请求完成", "挂起当前协程，切换执行其他就绪的协程", "为该请求创建新线程", "抛出超时异常"],
         "answer": 1,
         "explanation": "await 交出控制权，事件循环调度其他协程——单线程内靠协作式切换实现高并发 I/O。"},
        {"code": "PY_ASYNC", "title": "协程并发执行", "difficulty": "medium",
         "question": "要并发执行多个协程并收集全部结果，惯用方式是？",
         "options": ["依次 await 每个协程", "asyncio.gather(*coros)", "for 循环中 time.sleep(0)", "把协程放进 threading.Thread"],
         "answer": 1,
         "explanation": "逐个 await 是串行；gather 同时调度所有协程并按传入顺序返回结果列表。"},
        {"code": "PY_ASYNC", "title": "阻塞调用陷阱", "difficulty": "hard",
         "question": "在协程中直接调用 time.sleep(5) 的后果是？",
         "options": ["只挂起当前协程 5 秒", "阻塞整个事件循环，所有协程停摆 5 秒", "自动转换为 asyncio.sleep", "抛出 RuntimeError"],
         "answer": 1,
         "explanation": "time.sleep 是同步阻塞调用，会卡住事件循环唯一的线程；协程中应使用 await asyncio.sleep。"},
    ],
    "network": [
        {"code": "PY_SOCKET", "title": "TCP 与 UDP", "difficulty": "easy",
         "question": "TCP 相比 UDP 的核心特点是？",
         "options": ["无连接、传输更快", "面向连接、可靠传输、保证字节流顺序", "只能传输文本数据", "不需要端口号"],
         "answer": 1,
         "explanation": "TCP 三次握手建立连接，提供确认重传与按序交付；UDP 无连接低开销但不保证送达。"},
        {"code": "PY_SOCKET", "title": "服务端套接字流程", "difficulty": "medium",
         "question": "TCP 服务端套接字的标准调用顺序是？",
         "options": ["bind -> listen -> accept", "listen -> bind -> accept", "connect -> send -> recv", "accept -> bind -> listen"],
         "answer": 0,
         "explanation": "服务端先 bind 绑定地址端口，listen 进入监听，accept 阻塞等待客户端连接并返回会话套接字。"},
        {"code": "PY_HTTP_REG", "title": "HTTP 方法语义", "difficulty": "easy",
         "question": "按 REST 约定，创建资源通常使用哪个 HTTP 方法？",
         "options": ["GET", "POST", "DELETE", "HEAD"],
         "answer": 1,
         "explanation": "GET 幂等读取、POST 创建、PUT/PATCH 更新、DELETE 删除——语义化使用方法是 REST 设计的基础。"},
        {"code": "PY_HTTP_REG", "title": "requests 响应处理", "difficulty": "medium",
         "question": "resp = requests.get(url) 后，将 JSON 响应体解析为 Python 对象的惯用方式是？",
         "options": ["resp.text()", "resp.json()", "json.loads(resp)", "resp.body.json"],
         "answer": 1,
         "explanation": "resp.json() 直接反序列化响应体；resp.text 是字符串属性（非方法），json.loads 需要传入 resp.text。"},
        {"code": "PY_WEB_SRV", "title": "HTTP 报文结构", "difficulty": "medium",
         "question": "HTTP 请求报文中，请求头与请求体之间用什么分隔？",
         "options": ["一个分号", "一个空行（CRLF CRLF）", "一个制表符", "没有分隔符"],
         "answer": 1,
         "explanation": "起始行 + 若干头部行后跟一个空行，空行之后才是请求体——手写 socket HTTP 服务器时必须按此解析。"},
        {"code": "PY_WEB_SRV", "title": "状态码语义", "difficulty": "easy",
         "question": "HTTP 状态码 404 表示什么？",
         "options": ["服务器内部错误", "请求的资源不存在", "未授权访问", "请求成功但无内容"],
         "answer": 1,
         "explanation": "4xx 为客户端错误：404 资源不存在，401/403 与认证授权相关；500 是服务器内部错误，204 是成功无内容。"},
        {"code": "PY_WSGI_ASGI", "title": "WSGI 定位", "difficulty": "medium",
         "question": "WSGI 规范定义的是什么之间的接口？",
         "options": ["浏览器与服务器", "Web 服务器与 Python Web 应用/框架", "数据库与 ORM", "操作系统与解释器"],
         "answer": 1,
         "explanation": "WSGI 统一了服务器（gunicorn/uWSGI）调用 Python 应用的方式，框架只要实现 application(environ, start_response) 即可被任意 WSGI 服务器托管。"},
        {"code": "PY_WSGI_ASGI", "title": "ASGI 与异步", "difficulty": "hard",
         "question": "相比 WSGI，ASGI 的关键增强是什么？",
         "options": ["传输性能提升一倍", "原生支持异步应用与 WebSocket 等长连接协议", "内置数据库连接池", "自动生成 API 文档"],
         "answer": 1,
         "explanation": "WSGI 是同步单次请求-响应模型；ASGI 以 async 可调用为核心，支持 HTTP、WebSocket 等事件流，FastAPI 即构建在 ASGI 之上。"},
        {"code": "PY_WEB_FRAME", "title": "MVC 职责划分", "difficulty": "easy",
         "question": "MVC 模式中，Model 层的职责是？",
         "options": ["渲染页面模板", "处理数据与业务逻辑", "解析路由与请求分发", "管理静态资源"],
         "answer": 1,
         "explanation": "Model 承载数据结构与业务规则，View 负责展示，Controller 接收请求并协调二者。"},
        {"code": "PY_WEB_FRAME", "title": "路由的概念", "difficulty": "easy",
         "question": "Web 框架中的'路由（routing）'指的是什么？",
         "options": ["网络层的 IP 寻址", "将 URL 路径与处理函数建立映射关系", "数据库读写分离", "静态文件压缩策略"],
         "answer": 1,
         "explanation": "如 FastAPI 的 @app.get('/users/{id}')，框架按请求路径与方法找到对应处理函数并注入参数。"},
    ],
    "database": [
        {"code": "PY_DEBUG", "title": "异常捕获顺序", "difficulty": "medium",
         "question": "多个 except 分支的匹配规则是什么？",
         "options": ["按异常类名字母序匹配", "自上而下匹配第一个类型符合的分支，子类异常应放在父类之前", "所有匹配的分支都会执行", "只匹配最后一个分支"],
         "answer": 1,
         "explanation": "except 顺序敏感：若 except Exception 在前，后面的 except ValueError 永远不会命中。"},
        {"code": "PY_DEBUG", "title": "finally 语义", "difficulty": "medium",
         "question": "try-except-finally 中 finally 块的执行时机是？",
         "options": ["仅在无异常时执行", "仅在有异常时执行", "无论是否发生异常都会执行，常用于资源清理", "仅在 return 之后执行一次"],
         "answer": 2,
         "explanation": "finally 保证清理逻辑必然运行（即使 try 中 return 或抛异常），适合关闭文件、释放锁等收尾。"},
        {"code": "PY_TEST", "title": "断言与用例", "difficulty": "easy",
         "question": "pytest 中最基本的断言写法是？",
         "options": ["self.assertEqual(a, b)", "assert a == b", "expect(a).toBe(b)", "check(a, b)"],
         "answer": 1,
         "explanation": "pytest 直接使用 Python 原生 assert 并自动改写以给出详细失败信息；assertEqual 是 unittest 风格。"},
        {"code": "PY_TEST", "title": "fixture 机制", "difficulty": "medium",
         "question": "pytest 的 fixture 主要解决什么问题？",
         "options": ["并行执行测试", "为用例提供可复用的准备/清理逻辑与依赖注入", "生成测试覆盖率报告", "把测试编译为二进制"],
         "answer": 1,
         "explanation": "fixture 以函数参数名注入（如 db 会话、临时目录），yield 前是 setup、后是 teardown，多用例共享。"},
        {"code": "PY_IO", "title": "with 上下文管理", "difficulty": "easy",
         "question": "with open('a.txt') as f: 写法的核心好处是？",
         "options": ["读取速度更快", "代码块结束（含异常退出）时自动关闭文件", "自动创建不存在的文件夹", "文件内容自动转为 UTF-8"],
         "answer": 1,
         "explanation": "with 依赖上下文管理协议（__enter__/__exit__），无论正常结束还是抛异常都会释放资源。"},
        {"code": "PY_IO", "title": "Pathlib 用法", "difficulty": "medium",
         "question": "使用 pathlib 拼接路径的惯用写法是？",
         "options": ["Path('data') + 'a.txt'", "Path('data') / 'a.txt'", "Path.join('data', 'a.txt')", "Path('data').append('a.txt')"],
         "answer": 1,
         "explanation": "Path 重载了除法运算符做跨平台路径拼接；+ 不支持，os.path.join 是旧式 API。"},
        {"code": "PY_SQL", "title": "参数化查询", "difficulty": "medium",
         "question": "执行 SQL 时应使用参数化查询而非字符串拼接，主要原因是？",
         "options": ["拼接的 SQL 无法执行", "防止 SQL 注入攻击并正确处理转义", "参数化查询语法更短", "拼接会锁表"],
         "answer": 1,
         "explanation": "用户输入拼进 SQL 可被构造成恶意语句（注入）；占位符参数由驱动安全转义，如 cursor.execute(sql, (val,))。"},
        {"code": "PY_SQL", "title": "ORM 映射", "difficulty": "easy",
         "question": "SQLAlchemy ORM 的核心思想是什么？",
         "options": ["把 SQL 语句缓存到内存", "将数据库表映射为 Python 类、行映射为对象，以对象操作代替手写 SQL", "把数据库文件压缩存储", "用 NoSQL 替代关系型数据库"],
         "answer": 1,
         "explanation": "ORM 建立 类<->表、实例<->行 的映射，session.add/query 等对象操作由框架翻译为 SQL 执行。"},
        {"code": "PY_NUMPY_PANDAS", "title": "NumPy 向量化", "difficulty": "medium",
         "question": "NumPy 数组运算远快于等价的 Python for 循环，主要原因是？",
         "options": ["NumPy 自动使用 GPU", "向量化运算在底层以 C 实现，批量处理连续内存数据", "NumPy 默认开启多进程", "Python 循环会写磁盘"],
         "answer": 1,
         "explanation": "ndarray 是连续同质内存块，运算下沉到编译期优化的 C 循环，省去逐元素的解释器开销。"},
        {"code": "PY_NUMPY_PANDAS", "title": "Pandas 结构", "difficulty": "easy",
         "question": "Pandas 中承载二维表格数据的核心结构是？",
         "options": ["Series", "DataFrame", "ndarray", "Index"],
         "answer": 1,
         "explanation": "DataFrame 是带行列索引的二维表，每一列是一个 Series；groupby/merge 等统计操作围绕它展开。"},
    ],
}


async def seed_diagnostic_labs(session) -> int:
    """将诊断题库写入 labs（tag='diagnostic'）。幂等：已存在则跳过。返回写入数量。"""
    existing = (
        await session.execute(
            select(func.count()).select_from(Lab).where(Lab.tag == "diagnostic")
        )
    ).scalar() or 0
    if existing:
        print(f"[Seed] 诊断题库已存在 {existing} 题，跳过注入。")
        return 0

    nodes = {
        n.code: n.id
        for n in (await session.execute(select(KnowledgeNode))).scalars().all()
        if n.code
    }

    created = 0
    skipped_codes = set()
    for domain, questions in DIAGNOSTIC_QUESTIONS.items():
        for q in questions:
            node_id = nodes.get(q["code"])
            if node_id is None:
                skipped_codes.add(q["code"])
                continue
            session.add(Lab(
                title=q["title"],
                description=f"诊断测验（{domain}）",
                lab_type="quiz",
                difficulty=q.get("difficulty", "medium"),
                tag="diagnostic",
                node_id=node_id,
                test_cases={
                    "questions": [{
                        "id": "1",
                        "text": q["question"],
                        "options": q["options"],
                        "answer": q["answer"],
                        "explanation": q["explanation"],
                    }]
                },
                detailed_explanation=q["explanation"],
            ))
            created += 1

    await session.commit()
    if skipped_codes:
        print(f"[Seed] 诊断题跳过未知节点码: {sorted(skipped_codes)}")
    print(f"[Seed] 诊断题库注入完成: {created} 题。")
    return created
